spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/my_daily_hub
spring.datasource.username=my_daily_hub_user
spring.datasource.password=my_daily_hub_password

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true